# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano
    shield: corne_left
    snippet: studio-rpc-usb-uart
    artifact-name: corne_42_left
  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_42_right
  #- board: nice_nano
  #  shield: typeractive-corne_left nice_view_adapter nice_view
  #- board: nice_nano
  #  shield: typeractive-corne_right nice_view_adapter nice_view
  - board: nice_nano
    shield: crosses_left nice_view_adapter nice_view
    artifact-name: crosses_42_left

  - board: nice_nano
    shield: crosses_right nice_view_adapter nice_view
    #cmake-args: -DCONFIG_ZMK_STUDIO=y
    #snippet: studio-rpc-usb-uart
    artifact-name: crosses_42_right

